### ISSUE TITLE
Can you add support for rename-session please?

### ISSUE THREAD

**Issue by fgimian** [srsudar/tmux-completion#7]
Hey there, thanks so much for this! 😄 

I notice it doesn't work in completing session names when using rename-session:

```
usage: rename-session [-t target-session] new-name
```

This also includes a `rename` alias too:

```
     rename-session [-t target-session] new-name
                   (alias: rename)
             Rename the session to new-name.
```

When looking at `man tmux`, there are actually a lot more commands that allow you to specify session name too, e.g. kill-session, has-session .etc.  Not sure if it is also worth supporting those too?

Any help is greatly appreciated
Fotis

**Comment by fgimian** [comment]
I've just discovered https://github.com/imomaliev/tmux-bash-completion which seems to cover all my use cases, so feel free to close this if you don't wish to implement further completions mate 😄 

Thanks
Fotis

**Comment by srsudar** [comment]
Yeah that's the one I was going to send you. I need to update the README on this repo, because people occasionally still have questions. There was a PR [here](https://github.com/scop/bash-completion/pull/81#pullrequestreview-4141853) about merging it into default bash completions, and imomaliev's repo came up there too.

I've stopped using this myself. I'm a happy zsh user now.
